### ISSUE TITLE
Cannot use `useService` inside of services

### ISSUE THREAD

**Issue by TheUnlocked** [Exelord/solid-services#179]
This is the same issue as #43, which has now re-appeared. If you update the working demo posted on that issue (https://codesandbox.io/s/solid-services-bug-repro-6cohe4?file=/src/app.tsx) to the latest version of `solid-services`, it no longer works.

**Comment by Exelord** [comment]
Thank you for reporting! I will take a look on it

**Comment by Exelord** [comment]
So weird, I have a test for that is passing correctly 🤔

**Comment by TheUnlocked** [comment]
That fixed it. Thank you!
